# Generated by Django 4.2.5 on 2023-12-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_publisherhouse_year_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='is_publisher',
            field=models.BooleanField(default=True),
        ),
    ]
