# Generated by Django 4.2.5 on 2023-12-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_publisher_is_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='is_publisher',
        ),
        migrations.AlterField(
            model_name='publisherhouse',
            name='year_established',
            field=models.IntegerField(default=0),
        ),
    ]
