# Generated by Django 4.2.5 on 2023-10-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_profile_address_profile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
