# Generated by Django 4.2.5 on 2023-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField()),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('image_s', models.CharField(blank=True, max_length=50, null=True)),
                ('image_m', models.CharField(blank=True, max_length=50, null=True)),
                ('image_l', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
