# Generated by Django 4.2.5 on 2023-10-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_deletebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteBook',
        ),
    ]
